# -*- coding: utf-8 -*-
"""crime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RTeZPRKdInfC-v6RVCLjb2-zzMBbgA0x
"""

!pip install prophet

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from prophet import Prophet

a = pd.read_csv('Chicago_Crimes_2005_to_2007.csv',on_bad_lines='skip')
b = pd.read_csv('Chicago_Crimes_2008_to_2011.csv',on_bad_lines='skip')
c = pd.read_csv('Chicago_Crimes_2012_to_2017.csv',on_bad_lines='skip')

chicago_df = pd.concat([a,b,c])

chicago_df.shape

chicago_df.head()

plt.figure(figsize = (10,10))
sns.heatmap(chicago_df.isnull() , cbar = False , cmap = 'YlGnBu')

chicago_df.drop(['Unnamed: 0' ,
                 'Case Number' ,
                 'ID' ,
                 'IUCR' ,
                 'X Coordinate' ,
                 'Y Coordinate' ,
                 'Updated On' ,
                 'Year' ,
                 'FBI Code' ,
                 'Beat' ,
                 'Ward' ,
                 'Community Area' ,
                 'Location' ,
                 'District' ,
                 'Latitude' ,
                 'Longitude'] , inplace = True , axis = 1)

chicago_df.shape

chicago_df

chicago_df['Date'] = pd.to_datetime(chicago_df['Date'], errors='coerce')

chicago_df.Date

chicago_df.index = pd.DatetimeIndex(chicago_df.Date)

chicago_df['Primary Type'].value_counts()

chicago_df['Primary Type'].value_counts().iloc[:15]

order_data = chicago_df['Primary Type'].value_counts().iloc[:15].index.drop_duplicates()
order_data

plt.figure(figsize = (15,10))
sns.countplot(y = 'Primary Type' ,
              data = chicago_df ,
              order = order_data)

plt.figure(figsize = (15,10))
sns.countplot(y='Location Description',
              data = chicago_df,
              order = chicago_df['Location Description'].value_counts().iloc[:15].index.drop_duplicates())

chicago_df.resample('Y').size()

plt.plot(chicago_df.resample('Y').size())
plt.title('Crime Count Per Year')
plt.xlabel('Years')
plt.ylabel('Number of Crimes')

plt.plot(chicago_df.resample('M').size())
plt.title('Crime Count Per Year')
plt.xlabel('Years')
plt.ylabel('Number of Crimes')

plt.plot(chicago_df.resample('Q').size())
plt.title('Crime Count Per Quater')
plt.xlabel('Months')
plt.ylabel('Number of Crimes')

chicago_prophet = chicago_df.resample('M').size().reset_index()
 chicago_prophet

chicago_prophet.columns = ['Date' , 'Crime Count']
chicago_prophet

chicago_prophet_df_final = chicago_prophet.rename(columns = {'Date' : 'ds',
                                                                'Crime Count': 'y'})
chicago_prophet_df_final

m = Prophet()
m.fit(chicago_prophet_df_final)

future = m.make_future_dataframe(periods=750)
forecast = m.predict(future)
forecast

figure = m.plot(forecast , xlabel= 'Date' , ylabel= 'Crime Rate')

figure = m.plot_components(forecast)